name: todoapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen:
  image_picker: ^0.8.6
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.1.1
  http: ^0.13.5
  dio: ^4.0.6
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
   

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.otf
    - family: Poppins Black
      fonts:
        - asset: assets/fonts/Poppins-Black.otf
    - family: Poppins Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.otf
    - family: Poppins Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.otf
